# Generated by Django 4.2.4 on 2024-11-04 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="campaign", name="end_date",),
        migrations.RemoveField(model_name="campaign", name="start_date",),
    ]
