# Generated by Django 4.2.4 on 2024-11-20 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_campaign_qr_code_campaign_unique_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="points",
            field=models.IntegerField(default=0),
        ),
    ]
