# Generated by Django 4.2.4 on 2024-11-21 22:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0004_userprofile_points"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="redeemed_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="redeemed_campaigns",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
