# Generated by Django 4.2.4 on 2024-10-22 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_newsitem_userprofile_points_communitypost"),
    ]

    operations = [
        migrations.RemoveField(model_name="communitypost", name="author",),
        migrations.DeleteModel(name="NewsItem",),
        migrations.RemoveField(model_name="userprofile", name="points",),
        migrations.AddField(
            model_name="userprofile",
            name="is_complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="graduation_year",
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(name="CommunityPost",),
    ]
