# Generated by Django 5.1.3 on 2024-11-21 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_campaign_redeemed_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='campaign_pics/'),
        ),
    ]
