# Generated by Django 4.2.4 on 2024-12-02 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_activitylog"),
    ]

    operations = [
        migrations.RenameField(
            model_name="activitylog", old_name="description", new_name="details",
        ),
        migrations.RemoveField(model_name="activitylog", name="activity_type",),
        migrations.RemoveField(model_name="activitylog", name="points",),
        migrations.AddField(
            model_name="activitylog",
            name="action",
            field=models.CharField(default="Default Action", max_length=255),
        ),
    ]
