# Generated by Django 4.2.4 on 2024-12-02 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_rename_description_activitylog_details_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
