# Generated by Django 4.2.4 on 2024-12-02 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_alter_activitylog_timestamp"),
    ]

    operations = [
        migrations.RemoveField(model_name="activitylog", name="action",),
        migrations.RemoveField(model_name="activitylog", name="details",),
        migrations.AddField(
            model_name="activitylog",
            name="activity_type",
            field=models.CharField(
                choices=[("EARNED", "Earned Points"), ("REDEEMED", "Redeemed Points")],
                default="Default",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="activitylog",
            name="description",
            field=models.TextField(default="Default Action"),
        ),
        migrations.AddField(
            model_name="activitylog",
            name="points",
            field=models.IntegerField(default=0),
        ),
    ]
