# Generated by Django 4.2.4 on 2024-12-02 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_remove_activitylog_action_remove_activitylog_details_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="points",
            field=models.CharField(default="0", max_length=10),
        ),
    ]
