# Generated by Django 5.1.3 on 2024-12-10 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='newsfeed',
            field=models.BooleanField(default=False),
        ),
    ]
