# Generated by Django 5.1.3 on 2024-12-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.CharField(default='Unknown Author', max_length=200),
            preserve_default=False,
        ),
    ]
