# Generated by Django 5.1.4 on 2024-12-18 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_news_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='points',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
